### ISSUE TITLE
Changing channel

### ISSUE THREAD

**Issue by apexad** [ToddGreenfield/homebridge-directv#1]
These plug-ins might help you to implement changing the channel:

https://github.com/mmende/homebridge-samsungtv-control
https://github.com/TG908/homebridge-panasonictv

**Comment by ToddGreenfield** [comment]
Thanks. I implemented the ability to change channels in 0.0.6. A bit cumbersome with using the slider in Eve, but setting up a scene allows you to talk with Siri now. You can call the scene NBC and call it. Works nicely.

**Comment by apexad** [comment]
Nice! Great work.

**Comment by apexad** [comment]
Nice! It works great. Just one thing I noticed is that the max value is 500. Might want to make it 575 or 600. For DIRECTV, at least where I live, this will include all the premium channels.

Specifically in my case, HBO is on channel 501.

EDIT: I made a PR - https://github.com/ToddGreenfield/homebridge-directv/pull/2
