### ISSUE TITLE
Crash on loading in Home

### ISSUE THREAD

**Issue by ghost** [ToddGreenfield/homebridge-directv#14]
I get periodic crashes when opening the Home app in IOS.

directv-remote/index.js line 311, callback (null, parsedBody)

This callback has already been called by someone else, it can only be called one time.

**Comment by ToddGreenfield** [comment]
Can you paste the entire error please. I don't use this plugin anymore as I use a harmony hub, but will take a look.

**Comment by apexad** [comment]
FYI, I don’t use it anymore either. I no longer have DirectTV.

**Comment by ToddGreenfield** [comment]
Switched to Comcast myself- no more outages with storms.

**Comment by h00pak** [comment]
Here's the entire error. I started getting this only recently. I set up a scene in Eve to set a genie mini to a specific channel. This was working perfectly until recently--maybe the switch on the iPad I use as a hub to iOS 12.

/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/once.js:12
      throw new Error("This callback function has already been called by someone else; it can only be called one time.");
      ^

Error: This callback function has already been called by someone else; it can only be called one time.
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/once.js:12:13
    at /usr/local/lib/node_modules/homebridge-directv/index.js:103:9
    at /usr/local/lib/node_modules/homebridge-directv/node_modules/directv-remote/index.js:264:21
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/homebridge-directv/node_modules/directv-remote/index.js:311:17)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:186:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)

**Comment by apexad** [comment]
So it looks like callback on line 103 probably needs to get wrapped in a try...catch so this error is not fatal. Unclear how that callback is getting hit twice.

**Comment by mreassassin** [comment]
I'm getting the same thing.  it only happens when trying to use the eve scene remote on that accessory.

/usr/lib/node_modules/homebridge-directv/node_modules/directv-remote/index.js:311
                callback(null, parsedBody);
                ^
Error: This callback function has already been called by someone else; it can only be called one time.
    at /usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/once.js:12:13
    at /usr/lib/node_modules/homebridge-directv/index.js:149:9
    at /usr/lib/node_modules/homebridge-directv/node_modules/directv-remote/index.js:264:21
    at IncomingMessage.<anonymous> (/usr/lib/node_modules/homebridge-directv/node_modules/directv-remote/index.js:311:17)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)

this crashes homebridge.

i'm guessing this is, still, the only way (creating a scene in eve) to set a channel using siri with this plugin?

**Comment by apexad** [comment]
Anyone that still uses this plugin able to try the try-catch branch? should fix the crashes

**Comment by mreassassin** [comment]
I would love to give it a try.  (revisited this today) I had it working at one point today, then it started crashing again.

I can actually use Eve to control everything that Homekit does so my workaround is just never to open Homekit.  as soon as I do i get the crash.

any help would be greatly appreciated.

here's the crash:

> /usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/once.js:12
      throw new Error("This callback function has already been called by someone else; it can only be called one time.");
      ^

Error: This callback function has already been called by someone else; it can only be called one time.
    at /usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/once.js:12:13
    at /usr/lib/node_modules/homebridge-directv/index.js:103:9
    at /usr/lib/node_modules/homebridge-directv/node_modules/directv-remote/index.js:264:21
    at IncomingMessage.<anonymous> (/usr/lib/node_modules/homebridge-directv/node_modules/directv-remote/index.js:311:17)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)

**Comment by mreassassin** [comment]
not sure if anybody is still following this but here's a fix.  at line 103 of /usr/lib/node_modules/homebridge-directv/index.js copy paste this, **replacing the existing line 103**:

> 

 								try{callback(null, parseInt(response.major));}
								catch(Exception){
									//Do Nothing
								}

> 

I had to reach out to a friend after _trying_ and failing too many times (pun intended)!  
enjoy!

**Comment by ToddGreenfield** [comment]
Feel free to do a PR. I no longer maintain this plugin.

**Comment by janthony6** [comment]
> not sure if anybody is still following this but here's a fix. at line 103 of /usr/lib/node_modules/homebridge-directv/index.js copy paste this, **replacing the existing line 103**:
> 
> > 
> 
> ```
> 							try{callback(null, parseInt(response.major));}
> 							catch(Exception){
> 								//Do Nothing
> 							}
> ```
> > 
> 
> I had to reach out to a friend after _trying_ and failing too many times (pun intended)!
> enjoy!

This fixed the issue.  I was having this too.  Thanks to PM2 I had no idea the crash was happening since it would constantly restart.  Checked the logs and found it and then found this solution.

**Comment by apexad** [comment]
Fixed with #16 PR.
@ToddGreenfield can update npmjs to 1.04?

**Comment by ToddGreenfield** [comment]
Bumped npmjs to 1.0.4. Also added Alex as a maintainer on npm.
