### ISSUE TITLE
Wrong device type

### ISSUE THREAD

**Issue by edmarts** [ToddGreenfield/homebridge-directv#18]
Hi! I installed the plugin on homebridge and it detected my devices normally, but the main device he detected as an interruptor and the other devices as a motion sensor on my homebridge and homekit app. It's normal?

**Comment by apexad** [comment]
Yes, this is normal.  The main device is able to be turned on/off through the API (so it is shown as a switch), but the other devices cannot be turned on/off only queued for their status (so they are shown as motion detectors).
