### ISSUE TITLE
Multiple DVRs

### ISSUE THREAD

**Issue by cinsu** [ToddGreenfield/homebridge-directv#5]
I have multiple DVRs, an HR54 with several clients (genie mini( which I am able to successfully operate and 4 additional HR24 DVRs. I have added an additional platform each of the additional DVRs however it appears they are not detected. I have confirmed external access is allowed and I am able to issue ip commands from other platforms. 

```
[4/22/2017,` 5:30:50 PM] [MB HR24] Failed to find any DTV Locations (accessories) - Check IP address in config.json!
/usr/lib/node_modules/homebridge/lib/server.js:358
      for (var i = 0; i < foundAccessories.length; i++) {
                                          ^

TypeError: Cannot read property 'length' of null
    at Server.<anonymous> (/usr/lib/node_modules/homebridge/lib/server.js:358:43)
    at /usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/once.js:16:19
    at /usr/lib/node_modules/homebridge-directv/index.js:58:5
    at /usr/lib/node_modules/homebridge-directv/node_modules/directv-remote/index.js:262:21
    at IncomingMessage.<anonymous> (/usr/lib/node_modules/homebridge-directv/node_modules/directv-remote/index.js:306:25)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:188:7)
    at endReadableNT (_stream_readable.js:975:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
```

**Comment by apexad** [comment]
One of your boxes is the primary box (Likely the HR54?). You only need to setup a platform for that box and it should detect the other boxes automatically.

Keep in mind that as the plugin stands only the primary box can be powered on/off and Channel setting is implemented but not perfect.

**Comment by ToddGreenfield** [comment]
Are you able to ping the IP of the DVRs which are not working from where homebridge is running? Also try running the test1 file just uploaded to the files section (change your IP in the file).  
"node test1" from where the plugin is installed.
I have seen this error when the IP is not reachable for some reason, like after a router restart for example. The IP is "correct" but the STB/DVR can't connect to the network. I pulled the plug and restarted the unit. Once it reconnected everything was fine.
